### ISSUE TITLE
certificate.get_subject_ASN1()

### ISSUE THREAD

**Issue by pquerner** [ADVTOOLS/ADVTrustStore#23]
Hello,

I've posted some of this on the currently open PR #22 , but it got deleted since it doesnt belong there.
Maybe it belongs here and somebody can offer some help.

As I checked out the [Pull Request](https://github.com/manicmaniac/ADVTrustStore/tree/python3) I wanted to use the script like this:

`python3 iosCertTrustManager.py -a ~/.mitmproxy/mitmproxy-ca-cert.pem -y` 

But it fails with:

```
subject=CN = mitmproxy, O = mitmproxy

Importing to /Users/p.querner/Library/Developer/CoreSimulator/Devices/A7985F82-4E84-495E-A6CB-E044927B1F02/data/private/var/protected/trustd/private/TrustStore.sqlite3
Traceback (most recent call last):
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 796, in <module>
    program.run()
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 785, in run
    self.import_to_simulator(args.certificate_file, args.truststore)
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 691, in import_to_simulator
    tstore.add_certificate(cert)
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 507, in add_certificate
    self._add_record(certificate.get_fingerprint(self._hash), certificate.get_subject_ASN1(),
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 404, in get_subject_ASN1
    decoder.start(self._data)
  File "/Users/p.querner/projects/apps/ios/ADVTrustStore/iosCertTrustManager.py", line 220, in start
    raise Error('Expecting string instance.')
Error: Expecting string instance.
```

Cert:

```
cat ~/.mitmproxy/mitmproxy-ca-cert.pem
-----BEGIN CERTIFICATE-----
MIIDNTCCAh2gAwIBAgIUNivuiajD9UHl4ipAwiN0V8cty84wDQYJKoZIhvcNAQEL
BQAwKDESMBAGA1UEAwwJbWl0bXByb3h5MRIwEAYDVQQKDAltaXRtcHJveHkwHhcN
MjMwODAzMTU0MjQwWhcNMzMwODAyMTU0MjQwWjAoMRIwEAYDVQQDDAltaXRtcHJv
eHkxEjAQBgNVBAoMCW1pdG1wcm94eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJHvLj+h7k+8rZCR0w7r2J+yVI+CBop3gcl80PoFuT8otMPh0OHpdpSo
AEXz/+ygSSErdyWsMj5EMMxhCrrnQT9kEwKCdPSf57pePB6mkGiAcj1h6SQRp+Ow
IABH6IyxPmkBoShRDEkEYKSSc80OpFSXNa1L3lAhM8wSEOjjyfkBiMNkRwE5V5HR
qpoIZF5N8LcXpgzWCvaQIi+U6/620XWbO5638knoTr1iI0VzC8RnRGEJXRo8w8/Y
PFCVtLu4PkcDkJ9Fq0Znne5s+IlIkxsJlIRBVA3Gvu8Rd/yhs5Ji22nmruXbr0M3
OeY4BYSyakiL74KT4E3REEbADypCW4MCAwEAAaNXMFUwDwYDVR0TAQH/BAUwAwEB
/zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
FOnrUSRTp4F0Fs33LZTPAPqUrS2kMA0GCSqGSIb3DQEBCwUAA4IBAQB9hk5Yw+jZ
4fbZrYVhmARu41w8C9wqwyAa/nq99M77pLz0h11Gf98/nsLZylTFdrBHdGGlFmma
yeWcLf9d/ulPynYNqHysIZLEQxP7xMhtTkwAbHMTh6sqFVberZIx9hE0YuICDGRx
+AiCM+3Jbiaau/bY0iEkTOz/HIEjx53iScrFQwe680wlTHoGD2hgygAN/NEGmoEl
rMG4Y/Gp59mWgcK6TzRraihIPdGJeUI8YYs0azOiXIUcfHQbDFflTO/aZgCzrTNJ
jcwrfsgyuJZaNGJ2vTQWvhiIMPr7zULMtADLUlrs3qqN1HpKF33PyRhVUZ5DPq6v
BjUcHj5ohyWE
-----END CERTIFICATE-----
```

The cert was issued with mitmproxy.

```
mitmdump --version
Mitmproxy: 10.0.0
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  macOS-13.5-arm64-arm-64bit
```

Not sure what it means of if its related to the tool. If it isnt related, please close this issue.

**Comment by andrivet** [comment]
This PR has not been merged because it has issues. Please report to the author of the PR, not here.
